#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-sphinx_argparse
Version  : 0.3.1
Release  : 1
URL      : https://files.pythonhosted.org/packages/59/a1/69993f45da700fc842f6714f2062be3d5e2501be8a6cf20b9a133b72a295/sphinx-argparse-0.3.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/59/a1/69993f45da700fc842f6714f2062be3d5e2501be8a6cf20b9a133b72a295/sphinx-argparse-0.3.1.tar.gz
Summary  : A sphinx extension that automatically documents argparse commands and options
Group    : Development/Tools
License  : MIT
Requires: pypi-sphinx_argparse-license = %{version}-%{release}
Requires: pypi-sphinx_argparse-python = %{version}-%{release}
Requires: pypi-sphinx_argparse-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(poetry_core)

%description
No detailed description available

%package license
Summary: license components for the pypi-sphinx_argparse package.
Group: Default

%description license
license components for the pypi-sphinx_argparse package.


%package python
Summary: python components for the pypi-sphinx_argparse package.
Group: Default
Requires: pypi-sphinx_argparse-python3 = %{version}-%{release}

%description python
python components for the pypi-sphinx_argparse package.


%package python3
Summary: python3 components for the pypi-sphinx_argparse package.
Group: Default
Requires: python3-core
Provides: pypi(sphinx_argparse)
Requires: pypi(sphinx)

%description python3
python3 components for the pypi-sphinx_argparse package.


%prep
%setup -q -n sphinx-argparse-0.3.1
cd %{_builddir}/sphinx-argparse-0.3.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1639053322
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-sphinx_argparse
cp %{_builddir}/sphinx-argparse-0.3.1/LICENSE %{buildroot}/usr/share/package-licenses/pypi-sphinx_argparse/67de873c1e71bb7719e25d2209dc44bdfc755db4
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-sphinx_argparse/67de873c1e71bb7719e25d2209dc44bdfc755db4

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
